# Generated by Django 4.2.7 on 2025-12-30 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('tipo', models.CharField(choices=[('INFO', 'Informação'), ('SUCCESS', 'Sucesso'), ('WARNING', 'Aviso'), ('ERROR', 'Erro')], default='INFO', max_length=10, verbose_name='Tipo')),
                ('categoria', models.CharField(choices=[('CONSULTA', 'Consulta'), ('VACINA', 'Vacina'), ('EXAME', 'Exame'), ('PLANO', 'Plano'), ('SISTEMA', 'Sistema')], default='SISTEMA', max_length=20, verbose_name='Categoria')),
                ('lida', models.BooleanField(default=False, verbose_name='Lida')),
                ('lida_em', models.DateTimeField(blank=True, null=True, verbose_name='Lida em')),
                ('link', models.CharField(blank=True, max_length=500, null=True, verbose_name='Link de ação')),
                ('icone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ícone')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'db_table': 'notificacao',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='notificacao_user_id_79a717_idx'), models.Index(fields=['user', 'lida'], name='notificacao_user_id_354d23_idx')],
            },
        ),
    ]
