# Generated by Django 4.2.7 on 2025-12-30 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_notificacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='health_checks/%Y/%m/%d/')),
                ('predicted_condition', models.CharField(max_length=200)),
                ('condition_category', models.CharField(choices=[('PELE', 'Problemas de Pele'), ('OLHOS', 'Problemas Oculares'), ('OUVIDOS', 'Problemas Auriculares'), ('DENTAL', 'Problemas Dentários'), ('RESPIRATORIO', 'Problemas Respiratórios'), ('GASTROINTESTINAL', 'Problemas Gastrointestinais'), ('MUSCULOESQUELETICO', 'Problemas Musculoesqueléticos'), ('OUTRO', 'Outros')], default='OUTRO', max_length=50)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('urgency_level', models.CharField(choices=[('BAIXA', 'Monitorar - Não requer ação imediata'), ('MEDIA', 'Agendar Consulta - Recomendado em 3-7 dias'), ('ALTA', 'Urgência - Procurar veterinário imediatamente')], default='MEDIA', max_length=20)),
                ('recommendations', models.TextField(blank=True)),
                ('detected_symptoms', models.JSONField(blank=True, default=list)),
                ('processing_time', models.FloatField(default=0.0)),
                ('model_version', models.CharField(default='v1.0', max_length=50)),
                ('user_feedback', models.CharField(choices=[('CORRETO', 'Diagnóstico Correto'), ('PARCIAL', 'Parcialmente Correto'), ('INCORRETO', 'Incorreto'), ('NAO_AVALIADO', 'Não Avaliado')], default='NAO_AVALIADO', max_length=20)),
                ('veterinarian_diagnosis', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'health_checks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='notificacao',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='notificacao',
            name='notificacao_user_id_79a717_idx',
        ),
        migrations.RemoveIndex(
            model_name='notificacao',
            name='notificacao_user_id_354d23_idx',
        ),
        migrations.RemoveField(
            model_name='notificacao',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='notificacao',
            name='icone',
        ),
        migrations.RemoveField(
            model_name='notificacao',
            name='lida_em',
        ),
        migrations.RemoveField(
            model_name='notificacao',
            name='link',
        ),
        migrations.RemoveField(
            model_name='notificacao',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='notificacao',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='lida',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='mensagem',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='notificacao',
            table='notificacoes',
        ),
        migrations.AddField(
            model_name='healthcheck',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_checks', to='api.animal'),
        ),
    ]
