# Generated by Django 4.2.7 on 2025-12-30 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_healthcheck_alter_notificacao_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticoIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('imagem', models.ImageField(help_text='Imagem para análise', upload_to='diagnosticos/%Y/%m/', verbose_name='Imagem')),
                ('resultado', models.JSONField(default=dict, help_text='Resultado da predição (JSON com classes e probabilidades)', verbose_name='Resultado')),
                ('classe_predita', models.CharField(help_text='Classe com maior probabilidade', max_length=100, verbose_name='Classe Predita')),
                ('confianca', models.FloatField(help_text='Confiança da predição (0-1)', verbose_name='Confiança')),
                ('observacoes', models.TextField(blank=True, help_text='Observações do veterinário sobre o diagnóstico', verbose_name='Observações')),
                ('validado', models.BooleanField(default=False, help_text='Se o diagnóstico foi validado por um veterinário', verbose_name='Validado')),
                ('data_validacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Validação')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosticos_ia', to='api.animal', verbose_name='Animal')),
                ('validado_por', models.ForeignKey(blank=True, help_text='Veterinário que validou o diagnóstico', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnosticos_validados', to='api.veterinario', verbose_name='Validado Por')),
            ],
            options={
                'verbose_name': 'Diagnóstico IA',
                'verbose_name_plural': 'Diagnósticos IA',
                'db_table': 'api_diagnostico_ia',
                'ordering': ['-created_at'],
            },
        ),
    ]
