# Generated by Django 4.2.7 on 2025-12-30 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_diagnosticoia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosticoia',
            name='classe_predita',
            field=models.CharField(blank=True, default='', help_text='Classe com maior probabilidade', max_length=100, verbose_name='Classe Predita'),
        ),
        migrations.AlterField(
            model_name='diagnosticoia',
            name='confianca',
            field=models.FloatField(blank=True, help_text='Confiança da predição (0-1)', null=True, verbose_name='Confiança'),
        ),
        migrations.AlterField(
            model_name='diagnosticoia',
            name='resultado',
            field=models.JSONField(blank=True, default=dict, help_text='Resultado da predição (JSON com classes e probabilidades)', verbose_name='Resultado'),
        ),
    ]
