# Generated by Django 4.2.7 on 2025-12-31 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_fix_confianca_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacaoExterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS')], max_length=20)),
                ('evento', models.CharField(choices=[('consulta_agendada', 'Consulta Agendada'), ('consulta_confirmada', 'Consulta Confirmada'), ('lembrete_consulta', 'Lembrete de Consulta'), ('consulta_cancelada', 'Consulta Cancelada'), ('resultado_exame', 'Resultado de Exame'), ('vacina_vencendo', 'Vacina Vencendo'), ('aniversario_pet', 'Aniversário do Pet'), ('custom', 'Personalizada')], max_length=50)),
                ('destinatario', models.CharField(max_length=200)),
                ('assunto', models.CharField(blank=True, max_length=200)),
                ('mensagem', models.TextField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('enviada', 'Enviada'), ('erro', 'Erro')], default='pendente', max_length=20)),
                ('erro_mensagem', models.TextField(blank=True)),
                ('agendada_para', models.DateTimeField(blank=True, null=True)),
                ('enviada_em', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consulta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.consulta')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes_externas', to='api.tutor')),
            ],
            options={
                'db_table': 'notificacoes_externas',
                'ordering': ['-created_at'],
            },
        ),
    ]
