# Generated by Django 4.2.7 on 2026-01-01 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_tutor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='animals/%Y/%m/', verbose_name='Foto do Animal'),
        ),
        migrations.AddField(
            model_name='exame',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='exames/%Y/%m/', verbose_name='Arquivo do Exame'),
        ),
        migrations.AddField(
            model_name='exame',
            name='arquivo_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL do Arquivo'),
        ),
        migrations.AlterModelTable(
            name='animal',
            table='animals',
        ),
        migrations.AlterModelTable(
            name='exame',
            table='exames',
        ),
    ]
