# Generated by Django 4.2.7 on 2026-01-01 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0009_animal_photo_exame_arquivo_exame_arquivo_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prontuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('consulta', 'Consulta'), ('exame', 'Exame'), ('vacina', 'Vacina'), ('cirurgia', 'Cirurgia'), ('internacao', 'Internação'), ('retorno', 'Retorno')], max_length=20)),
                ('data', models.DateTimeField()),
                ('motivo', models.TextField()),
                ('sintomas', models.TextField(blank=True)),
                ('diagnostico', models.TextField(blank=True)),
                ('tratamento', models.TextField(blank=True)),
                ('observacoes', models.TextField(blank=True)),
                ('temperatura', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('frequencia_cardiaca', models.IntegerField(blank=True, null=True)),
                ('frequencia_respiratoria', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prontuarios', to='api.animal')),
                ('veterinario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prontuário',
                'verbose_name_plural': 'Prontuários',
                'db_table': 'prontuarios',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Prescricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamento', models.CharField(max_length=200, verbose_name='Medicamento')),
                ('dosagem', models.CharField(max_length=100, verbose_name='Dosagem')),
                ('via_administracao', models.CharField(max_length=100, verbose_name='Via de Administração')),
                ('frequencia', models.CharField(max_length=200, verbose_name='Frequência')),
                ('duracao', models.CharField(max_length=100, verbose_name='Duração')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data de Término')),
                ('orientacoes', models.TextField(blank=True, verbose_name='Orientações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('prontuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescricoes', to='api.prontuario')),
            ],
            options={
                'verbose_name': 'Prescrição',
                'verbose_name_plural': 'Prescrições',
                'db_table': 'prescricoes',
                'ordering': ['-data_inicio'],
            },
        ),
    ]
