# Generated by Django 4.2.7 on 2026-01-01 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='user',
            name='crmv',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CRMV'),
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='users/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('VETERINARIO', 'Veterinário'), ('ATENDENTE', 'Atendente'), ('RECEPCIONISTA', 'Recepcionista')], default='RECEPCIONISTA', max_length=20, verbose_name='Função'),
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
